name: unit-test
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches:
      - main
      - 'releases/**'
    paths:
      - '**.go'
      - '**go.mod'
      - '**go.sum'
jobs:
  test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Test
        run: make test-verbose